# Build System
# [build-system]
# requires = ["setuptools>=61.2.0"]
# build-backend = "setuptools.build_meta"

# Code style tools
[tool.black]
line-length = 150
target-version = ['py37', 'py38']

[tool.isort]
profile = "black"