# Pull base image
FROM condaforge/miniforge3:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="0904ae5f2ad79893ef3b81149de1c29922ebb2f91e32ef0b541f04094fb44195"
# Copy
WORKDIR /opt
COPY workflow/envs/env.yml .
# Environment
ENV PYTHONPATH="${PYTHONPATH}:$(pwd)"
RUN mamba env create -f env.yml && \
    mamba clean --all -y
# Run the command
CMD ["mamba", "run", "-n", "pset", "bash", "-x", "/opt/app/pool.sh"]
